name: Auto Update Bittensor Subnets

on:
  schedule:
    # Run every hour at the top of the hour
    - cron: "0 * * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-subnets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bittensor requests openai
        
    - name: Fetch subnet data from Bittensor blockchain
      run: |
        python scripts/fetch_subnets_bt.py
        
    - name: Generate subnet profiles
      run: |
        python scripts/build_profiles_local.py
        
    - name: Upload profiles to OpenAI
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python scripts/upload_to_openai.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "Auto-update subnet data and profiles [skip ci]"
        git push
