name: Update Subnets & Vector Store

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours (UTC)
  workflow_dispatch: {}      # allow manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Scrape TaoMarketCap
        run: python scripts/scrape_taomarketcap.py

      - name: Fetch Subnet Alpha descriptions
        run: python scripts/fetch_subnetalpha.py

      - name: Build profiles
        run: python scripts/build_profiles.py

      - name: Build vector store
        run: python scripts/build_vectorstore.py

      - name: Commit and push changes
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add -A
    git commit -m "Auto-update $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes"
    git pull --rebase origin main || true
    git push origin main || echo "Push failed"
