name: Bittensor Subnet Updater

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas bittensor openai

      - name: Fetch Bittensor subnet data
        env:
          OPENAI_API_KEY: ${{ secrets.Bittensor_Subnets }}
        run: |
          python scripts/fetch_subnets_bt.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add -A
          git commit -m "Auto-update $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes"
          git push origin main || echo "Push failed"

# 
